### ISSUE TITLE
Copy content to clipboard instead of opening in a browser

### ISSUE THREAD

**Issue by hoto** [FrederikRogalski/QR-Reader-Mac#1]
Hi there,

Great little service you've got here.
I've made a small adjustment to copy the content of the qr code to clipboard instead of opening it in the browser. Works flawlessly.

The `pbcopy` is a native preinstalled macos library which manages the clipboard. 

```applescript
on run {input, parameters}
	set dFolder to "~/Desktop/QRCodeHistory/"
	set filename to do shell script ("echo \"QR-Code-$(date +\"%Y-%m-%d-%H.%M.%S\").png\"")
	
	do shell script ("mkdir -p " & dFolder)
	do shell script (("screencapture " & dFolder & "\"" & filename & "\""))
	try
		do shell script ("echo " & dFolder & " | pbcopy")
		do shell script ("/usr/local/bin/zbarimg -q " & dFolder & filename & "| pbcopy")
	end try
	return input
end run
```

Also there have been some changes to the permissions and stuff in macos (e.g. have to add all apps to "Accessibility" which are gonna trigger this service, in my case I had to add Chrome as well as Automator). More [here ](https://apple.stackexchange.com/a/276839/275066).

**Comment by FrederikRogalski** [comment]
@hoto Thx, I tested it and it works like a charm. Immediately added this as a second workflow.
TODO:
Need to adjust the README.md
