### ISSUE TITLE
MAC OS X 13.2.1 (22D68) does not have a "general" category anymore?

### ISSUE THREAD

**Issue by Tapefabrik** [FrederikRogalski/QR-Reader-Mac#3]
Under Mac OS X Venture the action does not seem to be added anymore.

**Comment by FrederikRogalski** [comment]
True. I need to update the documentation to fit the new MacOS. You can find it at Keyboard > Keyboard Shortcuts... > Services > Shortcuts.

**Comment by FrederikRogalski** [comment]
I updated the README. Now it explains the process in MacOS Sonoma.
